// @flow
// @see https://developers.google.com/apps-script/reference/gas$Spreadsheet$Sheet/gas$Spreadsheet$Sheet

interface gas$Spreadsheet$Sheet {
  activate(): gas$Spreadsheet$Sheet;
  appendRow(rowContents: Object[]): gas$Spreadsheet$Sheet;
  autoResizeColumn(columnPosition: number): gas$Spreadsheet$Sheet;
  clear(): gas$Spreadsheet$Sheet;
  clear(options: Object): gas$Spreadsheet$Sheet;
  clearContents(): gas$Spreadsheet$Sheet;
  clearFormats(): gas$Spreadsheet$Sheet;
  clearNotes(): gas$Spreadsheet$Sheet;
  copyTo(gas$Spreadsheet$Sheet): gas$Spreadsheet$Sheet;
  deleteColumn(columnPosition: number): gas$Spreadsheet$Sheet;
  deleteColumns(columnPosition: number, howMany: number): void;
  deleteRow(rowPosition: number): gas$Spreadsheet$Sheet;
  deleteRows(rowPosition: number, howMany: number): void;
  getActiveCell(): gas$Spreadsheet$Range;
  getActivegas$Spreadsheet$Range(): gas$Spreadsheet$Range;
  getCharts(): gas$Spreadsheet$EmbeddedChart[];
  getColumnWidth(columnPosition: number): number;
  getDatagas$Spreadsheet$Range(): gas$Spreadsheet$Range;
  getFormUrl(): string;
  getFrozenColumns(): number;
  getFrozenRows(): number;
  getIndex(): number;
  getLastColumn(): number;
  getLastRow(): number;
  getMaxColumns(): number;
  getMaxRows(): number;
  getName(): string;
  getNamedRanges(): gas$Spreadsheet$NamedRange[];
  getParent(): gas$Spreadsheet$Sheet;
  getProtections(type: gas$Spreadsheet$ProtectionType): gas$Spreadsheet$Protection[];
  getRange(row: number, column: number): gas$Spreadsheet$Range;
  getRange(row: number, column: number, numRows: number): gas$Spreadsheet$Range;
  getRange(row: number, column: number, numRows: number, numColumns: number): gas$Spreadsheet$Range;
  getRange(a1Notation: string): gas$Spreadsheet$Range;
  getRowHeight(rowPosition: number): number;
  getSheetId(): number;
  getSheetName(): string;
  getSheetValues(startRow: number, startColumn: number, numRows: number, numColumns: number): Object[][];
  getTabColor(): string;
  hideColumn(column: number): void;
  hideColumns(columnIndex: number): void;
  hideColumns(columnIndex: number, numColumns: number): void;
  hideRow(row: gas$Spreadsheet$Range): void;
  hideRows(rowIndex: number): void;
  hideRows(rowIndex: number, numRows: number): void;
  hideSheet(): gas$Spreadsheet$Sheet;
  insertChart(chart: gas$Spreadsheet$EmbeddedChart): void;
  insertColumnAfter(afterPosition: number): gas$Spreadsheet$Sheet;
  insertColumnBefore(beforePosition: number): gas$Spreadsheet$Sheet;
  insertColumns(columnIndex: number): void;
  insertColumns(columnIndex: number, numColumns: number): void;
  insertColumnsAfter(afterPosition: number, howMany: number): gas$Spreadsheet$Sheet;
  insertColumnsBefore(beforePosition: number, howMany: number): gas$Spreadsheet$Sheet;
  insertImage(blob: gas$Blob, column: number, row: number): void;
  insertImage(blob: gas$Blob, column: number, row: number, offsetX: number, offsetY: number): void;
  insertImage(url: string, column: number, row: number): void;
  insertImage(url: string, column: number, row: number, offsetX: number, offsetY: number): void;
  insertRowAfter(afterPosition: number): gas$Spreadsheet$Sheet;
  insertRowBefore(beforePosition: number): gas$Spreadsheet$Sheet;
  insertRows(rowIndex: number): void;
  insertRows(rowIndex: number, numRows: number): void;
  insertRowsAfter(afterPosition: number, howMany: number): gas$Spreadsheet$Sheet;
  insertRowsBefore(beforePosition: number, howMany: number): gas$Spreadsheet$Sheet;
  isSheetHidden(): boolean;
  newChart(): gas$Spreadsheet$EmbeddedChartBuilder;
  protect(): gas$Spreadsheet$Protection;
  removeChart(chart: gas$Spreadsheet$EmbeddedChart): void;
  setActivegas$Spreadsheet$Range(range: gas$Spreadsheet$Range): gas$Spreadsheet$Range;
  setActiveSelection(range: gas$Spreadsheet$Range): gas$Spreadsheet$Range;
  setActiveSelection(a1Notation: string): gas$Spreadsheet$Range;
  setColumnWidth(columnPosition: number, width: number): gas$Spreadsheet$Sheet;
  setFrozenColumns(columns: number): void;
  setFrozenRows(rows: number): void;
  setName(name: string): gas$Spreadsheet$Sheet;
  setRowHeight(rowPosition: number, height: number): gas$Spreadsheet$Sheet;
  setTabColor(color: string): gas$Spreadsheet$Sheet;
  showColumns(columnIndex: number): void;
  showColumns(columnIndex: number, numColumns: number): void;
  showRows(rowIndex: number): void;
  showRows(rowIndex: number, numRows: number): void;
  showSheet(): gas$Spreadsheet$Sheet;
  sort(columnPosition: number): gas$Spreadsheet$Sheet;
  sort(columnPosition: number, ascending: boolean): gas$Spreadsheet$Sheet;
  unhideColumn(column: gas$Spreadsheet$Range): void;
  unhideRow(row: gas$Spreadsheet$Range): void;
  updateChart(chart: gas$Spreadsheet$EmbeddedChart): void;
}
