// @flow
// @seehttps://developers.google.com/apps-script/reference/jdbc/jdbc-result-set#updateobjectcolumnindex-x

interface gas$JdbcResultSet {
  absolute(row: number): boolean;
  afterLast(): void;
  beforeFirst(): void;
  cancelRowUpdates(): void;
  clearWarnings(): void;
  close(): void;
  deleteRow(): void;
  findColumn(columnLabel: string): number;
  first(): boolean	;
  getArray(columnIndex: number): gas$JdbcArray;
  getArray(columnLabel: string): gas$JdbcArray;
  getBigDecimal(columnIndex: number): number;
  getBigDecimal(columnLabel: string): number;
  getBlob(columnIndex: number): gas$JdbcBlob;
  getBlob(columnLabel: string): gas$JdbcBlob;
  getboolean(columnIndex: number): boolean;
  getboolean(columnLabel: string): boolean;
  getgas$Byte(columnIndex: number): gas$Byte;
  getgas$Byte(columnLabel: string): gas$Byte;
  getgas$Bytes(columnIndex: number): gas$Byte[];
  getgas$Bytes(columnLabel: string): gas$Byte[];
  getClob(columnIndex: number): gas$JdbcClob;
  getClob(columnLabel: string): gas$JdbcClob;
  getConcurrency(): number;
  getCursorName(): string;
  getDate(columnIndex: number): gas$JdbcDate;
  getDate(columnIndex: number, timeZone: string): gas$JdbcDate;
  getDate(columnLabel: string): gas$JdbcDate;
  getDate(columnLabel: string, timeZone: string): gas$JdbcDate;
  getDouble(columnIndex: number): Number;
  getDouble(columnLabel: string): Number;
  getFetchDirection(): number;
  getFetchSize(): number;
  getFloat(columnIndex: number): Number;
  getFloat(columnLabel: string): Number;
  getHoldability(): number;
  getInt(columnIndex: number): number;
  getInt(columnLabel: string): number;
  getLong(columnIndex: number): number;
  getLong(columnLabel: string): number;
  getMetaData(): gas$JdbcResultSetMetaData;
  getNClob(columnIndex: number): gas$JdbcClob;
  getNClob(columnLabel: string): gas$JdbcClob;
  getNstring(columnIndex: number): string;
  getNstring(columnLabel: string): string;
  getObject(columnIndex: number): Object;
  getObject(columnLabel: string): Object;
  getRef(columnIndex: number): gas$JdbcRef;
  getRef(columnLabel: string): gas$JdbcRef;
  getRow(): number;
  getRowId(columnIndex: number): gas$JdbcRowId;
  getRowId(columnLabel: string): gas$JdbcRowId;
  getSQLXML(columnIndex: number): gas$JdbcSQLXML;
  getSQLXML(columnLabel: string): gas$JdbcSQLXML;
  getShort(columnIndex: number): number;
  getShort(columnLabel: string): number;
  getStatement(): gas$JdbcStatement;
  getstring(columnIndex: number): string;
  getstring(columnLabel: string): string;
  getTime(columnIndex: number): gas$JdbcTime;
  getTime(columnIndex: number, timeZone: string): gas$JdbcTime;
  getTime(columnLabel: string): gas$JdbcTime;
  getTime(columnLabel: string, timeZone: string): gas$JdbcTime;
  getTimestamp(columnIndex: number): gas$JdbcTimestamp;
  getTimestamp(columnIndex: number, timeZone: string): gas$JdbcTimestamp;
  getTimestamp(columnLabel: string): gas$JdbcTimestamp;
  getTimestamp(columnLabel: string, timeZone: string): gas$JdbcTimestamp;
  getType(): number;
  getURL(columnIndex: number): string;
  getURL(columnLabel: string): string;
  getWarnings(): string[];
  insertRow(): void;
  isAfterLast(): boolean;
  isBeforeFirst(): boolean;
  isClosed(): boolean;
  isFirst(): boolean;
  isLast(): boolean	;
  last(): boolean;
  moveToCurrentRow(): void;
  moveToInsertRow(): void;
  next(): boolean;
  previous(): boolean;
  refreshRow(): void;
  relative(rows: number): boolean;
  rowDeleted(): boolean;
  rowInserted(): boolean;
  rowUpdated(): boolean;
  setFetchDirection(direction: number): void;
  setFetchSize(rows: number): void;
  updateArray(columnIndex: number, x: gas$JdbcArray): void;
  updateArray(columnLabel: string, x: gas$JdbcArray): void;
  updateBigDecimal(columnIndex: number, x: number): void;
  updateBigDecimal(columnLabel: string, x: number): void;
  updateBlob(columnIndex: number, x: gas$JdbcBlob): void;
  updateBlob(columnLabel: string, x: gas$JdbcBlob): void;
  updateboolean(columnIndex: number, x: boolean): void;
  updateboolean(columnLabel: string, x: boolean): void;
  updategas$Byte(columnIndex: number, x: gas$Byte): void;
  updategas$Byte(columnLabel: string, x: gas$Byte): void;
  updategas$Bytes(columnIndex: number, x: gas$Byte[]): void;
  updategas$Bytes(columnLabel: string, x: gas$Byte[]): void;
  updateClob(columnIndex: number, x: gas$JdbcClob): void;
  updateClob(columnLabel: string, x: gas$JdbcClob): void;
  updateDate(columnIndex: number, x: gas$JdbcDate): void;
  updateDate(columnLabel: string, x: gas$JdbcDate): void;
  updateDouble(columnIndex: number, x: number): void;
  updateDouble(columnLabel: string, x: number): void;
  updateFloat(columnIndex: number, x: number): void;
  updateFloat(columnLabel: string, x: number): void;
  updateInt(columnIndex: number, x: number): void;
  updateInt(columnLabel: string, x: number): void;
  updateLong(columnIndex: number, x: number): void;
  updateLong(columnLabel: string, x: number): void;
  updateNClob(columnIndex: number, x: gas$JdbcClob): void;
  updateNClob(columnLabel: string, x: gas$JdbcClob): void;
  updateNstring(columnIndex: number, x: string): void;
  updateNstring(columnLabel: string, x: string): void;
  updateNull(columnIndex: number): void;
  updateNull(columnLabel: string): void;
  updateObject(columnIndex: number, x: Object): void;
  updateObject(columnIndex: number, x: Object, scaleOrLength: number): void;
  updateObject(columnLabel: string, x: Object): void;
  updateObject(columnLabel: string, x: Object, scaleOrLength: number): void;
  updateRef(columnIndex: number, x: gas$JdbcRef): void;
  updateRef(columnLabel: string, x: gas$JdbcRef): void;
  updateRow(): void;
  updateRowId(columnIndex: number, x: gas$JdbcRowId): void;
  updateRowId(columnLabel: string, x: gas$JdbcRowId): void;
  updateSQLXML(columnIndex: number, x: gas$JdbcSQLXML): void;
  updateSQLXML(columnLabel: string, x: gas$JdbcSQLXML): void;
  updateShort(columnIndex: number, x: number): void;
  updateShort(columnLabel: string, x: number): void;
  updatestring(columnIndex: number, x: string): void;
  updatestring(columnLabel: string, x: string): void;
  updateTime(columnIndex: number, x: gas$JdbcTime): void;
  updateTime(columnLabel: string, x: gas$JdbcTime): void;
  updateTimestamp(columnIndex: number, x: gas$JdbcTimestamp): void;
  updateTimestamp(columnLabel: string, x: gas$JdbcTimestamp): void;
  wasNull(): boolean;
}
