// @flow
// @see https://developers.google.com/apps-script/reference/document/table-cell

interface gas$Document$TableCell {
  appendHorizontalRule(): gas$Document$HorizontalRule;
  appendImage(image: gas$BlobSource): gas$Document$InlineImage;
  appendImage(image: gas$Document$InlineImage): gas$Document$InlineImage;
  appendListItem(listItem: gas$Document$ListItem): gas$Document$ListItem;
  appendListItem(text: string): gas$Document$ListItem;
  appendParagraph(paragraph: gas$Document$Paragraph): gas$Document$Paragraph;
  appendParagraph(text: string): gas$Document$Paragraph;
  appendTable(): gas$Document$Table;
  appendTable(cells: string[][]): gas$Document$Table;
  appendTable(table: gas$Document$Table): gas$Document$Table;
  clear(): gas$Document$TableCell;
  copy(): gas$Document$TableCell;
  editAsText(): gas$Document$Text;
  findElement(elementType: gas$Document$ElementType): gas$Document$RangeElement;
  findElement(elementType: gas$Document$ElementType, from: gas$Document$RangeElement): gas$Document$RangeElement;
  findText(searchPattern: string): gas$Document$RangeElement;
  findText(searchPattern: string, from: gas$Document$RangeElement): gas$Document$RangeElement;
  getAttributes(): Object;
  getBackgroundColor(): string;
  getChild(childIndex: gas$Integer): gas$Document$Element;
  getChildIndex(child: gas$Document$Element): gas$Integer;
  getColSpan(): gas$Integer;
  getLinkUrl(): string;
  getNextSibling(): gas$Document$Element;
  getNumChildren(): gas$Integer;
  getPaddingBottom(): number;
  getPaddingLeft(): number;
  getPaddingRight(): number;
  getPaddingTop(): number;
  getParent(): gas$Document$ContainerElement;
  getParentRow(): gas$Document$TableRow;
  getParentTable(): gas$Document$Table;
  getPreviousSibling(): gas$Document$Element;
  getRowSpan(): gas$Integer;
  getText(): string;
  getTextAlignment(): gas$Document$TextAlignment;
  getType(): gas$Document$ElementType;
  getVerticalAlignment(): gas$Document$VerticalAlignment;
  getWidth(): number;
  insertHorizontalRule(childIndex: gas$Integer): gas$Document$HorizontalRule;
  insertImage(childIndex: gas$Integer, image: gas$BlobSource): gas$Document$InlineImage;
  insertImage(childIndex: gas$Integer, image: gas$Document$InlineImage): gas$Document$InlineImage;
  insertListItem(childIndex: gas$Integer, listItem: gas$Document$ListItem): gas$Document$ListItem;
  insertListItem(childIndex: gas$Integer, text: string): gas$Document$ListItem;
  insertParagraph(childIndex: gas$Integer, paragraph: gas$Document$Paragraph): gas$Document$Paragraph;
  insertParagraph(childIndex: gas$Integer, text: string): gas$Document$Paragraph;
  insertTable(childIndex: gas$Integer): gas$Document$Table;
  insertTable(childIndex: gas$Integer, cells: string[][]): gas$Document$Table;
  insertTable(childIndex: gas$Integer, table: gas$Document$Table): gas$Document$Table;
  isAtDocumentEnd(): boolean;
  merge(): gas$Document$TableCell;
  removeChild(child: gas$Document$Element): gas$Document$TableCell;
  removeFromParent(): gas$Document$TableCell;
  replaceText(searchPattern: string, replacement: string): gas$Document$Element;
  setAttributes(attributes: Object): gas$Document$TableCell;
  setBackgroundColor(color: string): gas$Document$TableCell;
  setLinkUrl(url: string): gas$Document$TableCell;
  setPaddingBottom(paddingBottom: number): gas$Document$TableCell;
  setPaddingLeft(paddingLeft: number): gas$Document$TableCell;
  setPaddingRight(paddingTop: number): gas$Document$TableCell;
  setPaddingTop(paddingTop: number): gas$Document$TableCell;
  setText(text: string): gas$Document$TableCell;
  setTextAlignment(textAlignment: gas$Document$TextAlignment): gas$Document$TableCell;
  setVerticalAlignment(alignment: gas$Document$VerticalAlignment): gas$Document$TableCell;
  setWidth(width: number): gas$Document$TableCell;
}
